### ISSUE TITLE
Random failure with TypeError: Cannot destructure property `vulnerabilities` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by sylvainlegault** [revathskumar/npm-audit-ci#8]
Hi,

I'm using version 1.1.0 and when executing npm-audit-cli back to back, sometime it will work but sometime it will fail with 

/node_modules/npm-audit-ci/index.js:42
  const {vulnerabilities} = metadata;
         ^

TypeError: Cannot destructure property `vulnerabilities` of 'undefined' or 'null'.

running report I get the following error
{
  "error": {
    "code": "ENOAUDIT",
    "summary": "Your configured registry (https://registry.npmjs.org/) does not support audit requests.",
    "detail": ""
  }
}

**Comment by bhardy** [comment]
We're having the same issue where this fails sometimes. I can reproduce it locally by rerunning the command (it seems to happen randomly), but it also happens in CI which should be fresh and it fails the build.

**Comment by joelday** [comment]
I'm seeing this same runtime error in a lerna based monorepo with the following output:
`Errors were found in your package-lock.json, run  npm install  to fix them.\n    Missing:`

**Comment by limonte** [comment]
same here, proof: https://travis-ci.org/sweetalert2/sweetalert2/builds/520209751

**Comment by sylvainlegault** [comment]
I created a PR to fix this
https://github.com/revathskumar/npm-audit-ci/pull/10

**Comment by revathskumar** [comment]
Merged #10. released `1.2.0`. 
Closing this issue for now.
